### ISSUE TITLE
Shared folder problem - No guest additions were detected on the base box for this VM!...

### ISSUE THREAD

**Issue by ucassh** [gfreeau/php7play#1]
Hi,

during 

```
$ vagrant up
```

I had one problem:

>    default: No guest additions were detected on the base box for this VM! Guest
>    default: additions are required for forwarded ports, shared folders, host only
>    default: networking, and more. If SSH fails on this machine, please install
>    default: the guest additions and repackage the box to continue.

Problem was in my environment, and solution for this was:

```
vagrant plugin install vagrant-vbguest
```

I think, it might be helpful for those who had the same :)

**Comment by gfreeau** [comment]
Ok thanks for posting your solution.

**Comment by hex2dec** [comment]
Thanks for your solution.

**Comment by Komalbandi** [comment]
Thank you for your solution.

**Comment by magicalbob** [comment]
Thanks @ucassh 

Interestingly I only got the "No guest additions" issue with the 2 CentOS 7 machines in my Vagrantfile, the CentOS 6 machines in it started fine & /vagrant was accessible.

**Comment by SoccerGee** [comment]
+1 thank you for posting @ucassh

**Comment by JulienDERONGS** [comment]
Thanks :]

**Comment by dxtkdxtk** [comment]
thanks!
